name: Run Tests

on:
  pull_request:
    branches: [ main ]
    paths:
    -  'examples/*'
    -  'pwncollege/*'
    -  'pwncollege/pwncli/*'
    -  'tests/*'
  push:
    branches: [ main ]
    paths:
    -  'examples/*'
    -  'pwncollege/*'
    -  'tests/*'
  workflow_dispatch: {} 


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.12.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry pytest pytest-cov mypy paramiko types-requests types-paramiko
          poetry install
      - name: Run tests, save ssh key and generate coverage report
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          TEST_PASSWORD='${{ secrets.TEST_PASSWORD }}' python3 -m pytest --cov=pwncollege --cov-report=xml
      - name: Perform type checking
        run: |
            python3 -m mypy pwncollege
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          path_to_write_report: ./codecov_report.gz
